categories:
    - Ecology
owner: ecology
remote_repository_url: https://github.com/Marie59/Sentinel_2A/SRS_tools
long_description: |
  Compute biodiveristy indicators from Sentinel 2 remote sensing data
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for spatial remote sensing tool: {{ tool_name }}."
suite:
  name: "Sentinel_2A"
  description: "A suite of indicators for remote sensing data"
  type: repository_Sentinel_2A
